### ISSUE TITLE
Issue with deploy-infra action on 3.2.4 due to missing ffmpeg

### ISSUE THREAD

**Issue by conantp** [CouncilDataProject/cdp-backend#215]
### Describe the Bug

After merging in the PRs for 3.2.4, I'm receiving an error on the deploy-infra action due to missing ffmpeg:

```
Traceback (most recent call last):
[16](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:17)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/bin/get_cdp_infrastructure_stack", line 5, in <module>
[17](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:18)
    from cdp_backend.bin.get_cdp_infrastructure_stack import main
[18](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:19)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/cdp_backend/bin/get_cdp_infrastructure_stack.py", line 12, in <module>
[19](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:20)
    from cdp_backend.database import DATABASE_MODELS
[20](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:21)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/cdp_backend/database/__init__.py", line 9, in <module>
[21](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:22)
    from . import models
[22](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:23)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/cdp_backend/database/models.py", line 12, in <module>
[23](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:24)
    from ..utils import file_utils
[24](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:25)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/cdp_backend/utils/file_utils.py", line 14, in <module>
[25](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:26)
    import ffmpeg
[26](https://github.com/sunshine-request/cdp-asheville/actions/runs/3160571018/jobs/5145176005#step:9:27)
ModuleNotFoundError: No module named 'ffmpeg'
```

### Expected Behavior

Successful execution of deploy-infra action.

### Reproduction

I'm not sure if there's anything specific to my instance, but I think you could probably reproduce this behavior by setting up an instance at 3.2.3, applying the PRs generate for 3.2.4, and watching the "Action" results. 

### Environment

https://github.com/sunshine-request/cdp-asheville

**Comment by evamaxfield** [comment]
Nice catch!!! Thank you! Will fix and release a new version
